### PR TITLE
added support for the "extends" keyword

### PR DESCRIPTION
**Pull request by alesandroLang**
Hi Boris,

this should add support for the "extends" keyword of json schema.
Feel free to edit anything you don't like when it comes to code style.

Regards
Alesandro

### CODE REVIEW

**Comment by bcherny** [comment]
@alesandroLang Sorry for the delay, I was out of town. This is excellent - thanks for the contribution!

**Comment by bcherny** [comment]
```
+ json-schema-to-typescript@4.6.0
```

**Comment by alesandroLang** [comment]
then we might close #5

**Comment by bcherny** [comment]
Done.

**Pull request merged**
