### PR TITLE
Allow unicode (Fixes #279)

### LINKED ISSUE #279: Allow unicode characters in type name
https://github.com/bcherny/json-schema-to-typescript/blob/d898361ff973d3746ea695f1efce75c975061c6f/src/utils.ts#L164

The member of type name is restricted to only english letters (and some symbol)
Typescript now allows unicode characters ([doc link](https://www.typescriptlang.org/docs/handbook/release-notes/overview.html#better-unicode-support-for-identifiers))

So, modify this function to allow unicode characters in type name, or as an option?

### PR DESCRIPTION
**Pull request by iansw246**
Fixes #279 and other issues relating to invalid characters in identifiers. It will cover the functionality of #538 

This allows any type name that is valid in ES5 by removing invalid characters. Valid characters were determined according to https://mathiasbynens.be/notes/javascript-identifiers.

It uses lodash.template, regenerate, and unicode-11.0.0 to generate the regex in scripts/generate-identifier-regex.ts

It uses code from this gist https://gist.github.com/mathiasbynens/6334847

There is no given license, so I'm not sure if we can use that. 

If we can target ES6 or newer, this code can be significantly simplified with Unicode-aware regex.

### CODE REVIEW

**Comment by TravisChong** [comment]
@bcherny Could we get a timeframe for when this will be reviewed, thanks :).

**Review by bcherny — CHANGES_REQUESTED** [review]
Thanks for the contribution, and sorry for the delay!

I'm supportive of this change, but would love to see a simpler implementation. Can we just use https://www.npmjs.com/package/identifierfy (or a similar external library) instead?

cc @mathiasbynens, in case you have a recommendation for the right NPM module to use for coercing strings to valid JS/TS identifiers.

**Comment by iansw246** [comment]
Would the Unicode-aware regex in the latest commit work? This doesn't require any other packages nor the regex-generation scripts.

**Comment by iansw246** [comment]
I tried using identifierfy but faced some issues when toSafeString was called on the output of toSafeString. It also is a bit conservative, removing more than the minimum in some cases. Ultimately, using identifierfy should work with a few changes to calls of toSafeString

**Comment by bcherny** [comment]
> I tried using identifierfy but faced some issues when toSafeString was called on the output of toSafeString. Also, it removes more than the minimum in some cases. Ultimately, using identifierfy should work with a few changes to calls of toSafeString

Great -- want to try doing this?

**Comment by iansw246** [comment]
I've gotten Identifierfy to work

I've had to remove several calls to toSafeString() to prevent double conversion. This should be OK since the parser converts standaloneNames with generateName()

**Comment by bcherny** [comment]
Closing out stale PRs.

**Pull request closed without merging**
