### PR TITLE
Fix 'cannot use in operator' error

### PR DESCRIPTION
**Pull request by ohana54**
Took the great work done here #284 and added a test

### CODE REVIEW

**Comment by ohana54** [comment]
@bcherny Hi, could you please take a look at this PR when you have some time?
Thanks!

**Comment by felixfbecker** [comment]
@bcherny this is still blocking our upgrade from v6 - would you have a moment to take a look at this fix by any chance?

**Comment by bcherny** [comment]
Published `9.1.1`

**Comment by ohana54** [comment]
Thank you @bcherny!

**Pull request merged**
