### PR TITLE
Deep schema

### PR DESCRIPTION
**Pull request by darcyparker**
Reduces size of call stack for https://github.com/bcherny/json-schema-to-typescript/issues/35

@donaldpipowitch can you test this branch?

There is more opportunity to improve. But it may not be necessary.

### CODE REVIEW

**Comment by donaldpipowitch** [comment]
I'll try it. Thanks.

**Comment by donaldpipowitch** [comment]
It looks like it still throws, but at a different line:

```
/Users/donaldpipowitch/Workspace/json-schema-to-typescript/dist/index.js:173
    Compiler.prototype.generateTsType = function (rule, propName, isTop, isReference) {
                                                 ^

RangeError: Maximum call stack size exceeded
    at Compiler.generateTsType (/Users/donaldpipowitch/Workspace/json-schema-to-typescript/dist/index.js:173:50)
    at Compiler.toTsType (/Users/donaldpipowitch/Workspace/json-schema-to-typescript/dist/index.js:220:25)
    at /Users/donaldpipowitch/Workspace/json-schema-to-typescript/dist/index.js:201:94
    at Array.map (native)
    at Compiler.generateTsType (/Users/donaldpipowitch/Workspace/json-schema-to-typescript/dist/index.js:201:62)
    at Compiler.toTsType (/Users/donaldpipowitch/Workspace/json-schema-to-typescript/dist/index.js:220:25)
    at Compiler.resolveRef (/Users/donaldpipowitch/Workspace/json-schema-to-typescript/dist/index.js:142:24)
    at Compiler.generateTsType (/Users/donaldpipowitch/Workspace/json-schema-to-typescript/dist/index.js:203:29)
    at Compiler.toTsType (/Users/donaldpipowitch/Workspace/json-schema-to-typescript/dist/index.js:220:25)
    at Compiler.generateTsType (/Users/donaldpipowitch/Workspace/json-schema-to-typescript/dist/index.js:191:78)
```

**Comment by darcyparker** [comment]
Ok - great. Sounds like its' getting better. The next piece to focus on is `toTsDeclaration()` call of `this.toTsType()` which calls `generateTsType()` which sometimes calls `toTsDeclaration()` again...

I commented about this recursion here:
https://github.com/darcyparker/json-schema-to-typescript/blob/c6396e19d7e1ff213d33c3b39a5716e7710d9d8a/src/index.ts#L300-L302

Trampolining may be a good approach. But @bcherny may have some other thoughts too? I can continue to think about it over the next few days to see if I have more thoughts on how to optimize.

**Comment by bcherny** [comment]
I'll take a look tonight/this week. Thanks for the investigation @darcyparker

**Comment by darcyparker** [comment]
Note: removing lodash `zip` benefit is questionable... I did it as an experiment. It works. But performance isn't better. There is < dependency on lodash though.

**Comment by darcyparker** [comment]
@bcherny - I have a trampoline in place and it is allowing more depth.  Not sure if you want to go with this or not...

**Comment by bcherny** [comment]
@darcyparker I'd like to look into it more before going for a bandaid - this seems like an issue that needs a real fix.

**Comment by darcyparker** [comment]
ok - np. I will take a break.

**Comment by bcherny** [comment]
@darcyparker As always, thanks for all the help. Will keep you posted.

**Comment by bcherny** [comment]
This was an issue with the schema, not with the compiler. See https://github.com/bcherny/json-schema-to-typescript/issues/35#issuecomment-250076988.

**Pull request closed without merging**
