### PR TITLE
Add normalizer rules for $defs and const

### PR DESCRIPTION
**Pull request by awlayton**
This adds support for newer keywords which have previous equivalents:

- [`$defs`][] is mapped to `definitions`
- [`const`][] is mapped to a singleton `enum`

[`$defs`]:https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.appendix.G
[`const`]: https://json-schema.org/understanding-json-schema/reference/generic.html#constant-values

### CODE REVIEW

**Comment by bcherny** [comment]
Thanks for the contribution! Mind adding some basic tests to make sure this doesn’t regress in the future?

**Comment by MaikuMori** [comment]
It would be nice to have this merged since other tooling has already moved to https://json-schema.org/draft/2019-09/schema.

**Comment by edzis** [comment]
@bcherny Are the tests fine?

**Review by bcherny — APPROVED** [review]
Looks great. Thank you for the contribution!

**Review by bcherny — CHANGES_REQUESTED** [review]
Mind rebasing? Then I'll go ahead and merge.

**Review by bcherny — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
