### PR TITLE
Update to Glob 10

### LINKED ISSUE #587: Update to glob 10
The current version of glob in this package has an indirect security vulnerability from [inflight](https://security.snyk.io/package/npm/inflight), glob can be updated to v10, and glob-promise can be removed since newer versions of glob are async.

### PR DESCRIPTION
**Pull request by evert**
We've been dealing with some Typescript issues in our codebase for a while, and tracing everything back I believe upgrading Glob should fix this.

Unfortunately I had some build issues that I didn't fully understand and seemed unrelated to this change.

Lmk what I can do get this merged!

Edit: upon some further inspection I this is similar to #590 .

Fixes #587

### CODE REVIEW

**Comment by evert** [comment]
This PR causes one test to fail:

```
  ✖ files in (-i), pipe out Did not match snapshot
```

```
  files in (-i), pipe out

  Did not match snapshot

  Difference:

    `/* eslint-disable */␊
    /**␊
     * This file was automatically generated by json-schema-to-typescript.␊
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,␊
     * and run json-schema-to-typescript to regenerate this file.␊
     */␊
    ␊
  - export interface BSchema {␊
  -   x?: string;␊
  -   y: number;␊
  -   [k: string]: unknown;␊
  - }␊
  - /* eslint-disable */␊
  + export interface ASchema {␊
  +   f: string;␊
  +   g?: number;␊
  + }␊
  + /* eslint-disable */␊
    /**␊
     * This file was automatically generated by json-schema-to-typescript.␊
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,␊
     * and run json-schema-to-typescript to regenerate this file.␊
     */␊
    ␊
  - export interface ASchema {␊
  -   f: string;␊
  -   g?: number;␊
  + export interface BSchema {␊
  +   x?: string;␊
  +   y: number;␊
  +   [k: string]: unknown;␊
    }␊
    `

  › <anonymous> (test/testCLI.ts:107:7)

```

**Comment by evert** [comment]
For some reason that test failed because the output came out in a different order. I rebuilt the snapshots, so this should be good to go now!

**Comment by bcherny** [comment]
Thanks for the contribution! Done in 4f4795275b184f32a14f621c60a9c89b8cc0fd86, since it needed some other upgrades + test fixes.

**Comment by evert** [comment]
Thank you! Can finally remove a bunch of awkward workarounds! 😍

**Comment by evert** [comment]
You should remove @types/glob too!

**Comment by bcherny** [comment]
Published 14.0.2.

**Pull request closed without merging**
