### PR TITLE
Add option to generate TS string enums

### PR DESCRIPTION
**Pull request by codan84**
Linked issue: https://github.com/bcherny/json-schema-to-typescript/issues/200
Addressed comments/requests in: https://github.com/bcherny/json-schema-to-typescript/pull/262#pullrequestreview-324907958

Implemented as a normalizer under cli/options flag: `inferStringEnumKeysFromValues`

### CODE REVIEW

**Review by bcherny — CHANGES_REQUESTED** [review]
Thanks for the contribution! Would you mind adding a couple e2e tests too, so we have a record of the end to end output with this flag enabled?

**Comment by codan84** [comment]
> Thanks for the contribution! Would you mind adding a couple e2e tests too, so we have a record of the end to end output with this flag enabled?

Added e2e test

**Comment by codan84** [comment]
@bcherny ping.
I could really do with this feature being available as we have a lot of issues with `tsEnumNames` when converting to OpenAPI schema.

**Comment by codan84** [comment]
@bcherny ping #2

**Comment by codan84** [comment]
How come this one is still not merged? I addressed all change requests and am updating all conflicts regularly. Can we merge this one please?

**Review by bcherny — APPROVED** [review]
Looks good! Thanks for the contribution.

**Comment by bcherny** [comment]
Mind rebasing one last time?

**Comment by codan84** [comment]
Rebased

**Comment by bcherny** [comment]
Published json-schema-to-typescript@14.1.0

**Pull request merged**
