### PR TITLE
Add readonly support

### PR DESCRIPTION
**Pull request by mattroberts297**
Because I wanted to enforce some immutability

_PS Thanks for the awesome library / tool_

### CODE REVIEW

**Comment by jameswilddev** [comment]
This looks like it would resolve #131, excepting the use of ReadOnlyArray.  Do you know if it would also turn `{ [k: string]: T }` into `{ readonly [k: string]: T}`?

**Comment by bcherny** [comment]
Looks good, but I'd love if you could iterate on this a bit more before we merge it (also, sorry for the delay in getting to this!).

1. Please rename the option to `--readonly`.
2. Could you make sure it also makes index signatures (as @jameswilddev noted), array types, tuple types, and referenced types readonly?
3. Please also update README.md to document this.

**Comment by jonaskello** [comment]
I'm also looking for this function, is someone still working on it?

**Comment by mattroberts297** [comment]
I stopped working on this PR because I moved away from the language (as opposed to the library) for a time. Thanks for the feedback and apologies for not addressing it.

**Comment by codingismy11to7** [comment]
I'm guessing this PR will probably get closed, but just wanted to chime in that I'd additionally expect
```typescript
export type X = Base & {
  field: type
};
```

to output as 
```typescript
export type X = Base & Readonly<{
  field: type
}>;
```

which this code doesn't seem to address

**Comment by bcherny** [comment]
https://github.com/bcherny/json-schema-to-typescript/pull/412

**Pull request closed without merging**
