### PR TITLE
Use tinyglobby for globbing

### PR DESCRIPTION
**Pull request by benmccann**
Closes https://github.com/bcherny/json-schema-to-typescript/issues/623

I can't reopen the previous PR, so creating this as a new one

### CODE REVIEW

**Comment by benmccann** [comment]
@bcherny I was wondering if you might have a chance to take a look at this PR? thanks!

**Review by bcherny — APPROVED** [review]
LG! Thanks for the contribution!

**Comment by bcherny** [comment]
Published 15.0.3.

**Comment by benmccann** [comment]
awesome. thank you!!

**Pull request merged**
