### PR TITLE
compileFromDir (aka batch compile)

### PR DESCRIPTION
**Pull request by tomholford**
Consider this a WIP implementation to address #16 

Call `compileFromDir` with a list of filenames and the optional options hash (same method signature as `compileFromFile`)

todo:
- [ ] Tests 
- [ ] CLI support

### CODE REVIEW

**Comment by tomholford** [comment]
@bcherny Both :) Sketched out an idea to address #16 and wanted to see if it's congruent with your roadmap before investing more time into it. Further, wanted to solicit feedback on the interface - i.e. should this be available via CLI? And if so, what would the command look like?

For example:
```
json2ts -d schemas/models/ -R
```
where `-d` indicates the directory for compilation and `-R` indicates to traverse the directory recursively

**Comment by bcherny** [comment]
@tomholford See this comment and the one after it - does that seem reasonable to you?

https://github.com/bcherny/json-schema-to-typescript/issues/16#issuecomment-282951441

**Comment by bcherny** [comment]
@tomholford Closing for inactivity. Feel free to reopen when/if you get back to this.

**Comment by tomholford** [comment]
@bcherny Thanks, will re-open later

**Pull request closed without merging**
